export const FROM_PLAIN = 'FROM_PLAIN'
export const FROM_INSTANCE = 'FROM_INSTANCE'
export const ROOT_CREATE = 'ROOT_CREATE'
export const ROOT_UPDATE = 'ROOT_UPDATE'
export const ADMIN_CREATE = 'ADMIN_CREATE'
export const ADMIN_UPDATE = 'ADMIN_UPDATE'
export const USER_CREATE = 'USER_CREATE'
export const USER_UPDATE = 'USER_UPDATE'
