export enum OrganizationSettingsType {
	PRODUCT_GROUP = 'PRODUCT_GROUP',
	PRODUCT_UNIT = 'PRODUCT_UNIT',
	PRODUCT_ROUTE = 'PRODUCT_ROUTE',
	PROCEDURE_GROUP = 'PROCEDURE_GROUP',

	SYSTEM_SETTING = 'SYSTEM_SETTING',

	SCREEN_PRODUCT_LIST = 'SCREEN_PRODUCT_LIST',

	SCREEN_RECEIPT_LIST = 'SCREEN_RECEIPT_LIST',
	SCREEN_RECEIPT_DETAIL = 'SCREEN_RECEIPT_DETAIL',
	SCREEN_RECEIPT_UPSERT = 'SCREEN_RECEIPT_UPSERT',

	SCREEN_INVOICE_LIST = 'SCREEN_INVOICE_LIST',
	SCREEN_INVOICE_DETAIL = 'SCREEN_INVOICE_DETAIL',
	SCREEN_INVOICE_UPSERT = 'SCREEN_INVOICE_UPSERT',

	SCREEN_CUSTOMER_LIST = 'SCREEN_CUSTOMER_LIST',
	SCREEN_CUSTOMER_DETAIL = 'SCREEN_CUSTOMER_DETAIL',

	SCREEN_DISTRIBUTOR_LIST = 'SCREEN_DISTRIBUTOR_LIST',
	SCREEN_DISTRIBUTOR_DETAIL = 'SCREEN_DISTRIBUTOR_DETAIL',

	SCREEN_PROCEDURE_LIST = 'SCREEN_PROCEDURE_LIST',
	SCREEN_PROCEDURE_DETAIL = 'SCREEN_PROCEDURE_DETAIL',
}
