export { default as IconClose } from './IconClose.vue'
export { default as IconPlus } from './IconPlus.vue'
export { default as IconPrint } from './IconPrint.vue'
export { default as IconSave } from './IconSave.vue'
export { default as IconTrash } from './IconTrash.vue'
