export enum SOCKET_EVENT {
  SERVER_EMIT_DEMO = 'SERVER_EMIT_DEMO',
  SERVER_EMIT_VISIT_CREATE = 'SERVER_EMIT_VISIT_CREATE',
  CLIENT_EMIT_VISIT_CREATE = 'CLIENT_EMIT_VISIT_CREATE',

  DISTRIBUTOR_UPSERT = 'DISTRIBUTOR_UPSERT',
  CUSTOMER_UPSERT = 'CUSTOMER_UPSERT',
  PRODUCT_UPSERT = 'PRODUCT_UPSERT',
  PRODUCT_LIST_UPDATE = 'PRODUCT_LIST_UPDATE',
  BATCH_UPSERT = 'BATCH_UPSERT',
  BATCH_LIST_UPDATE = 'BATCH_LIST_UPDATE',
  PROCEDURE_UPSERT = 'PROCEDURE_UPSERT',

  VISIT_CREATE = 'VISIT_CREATE',
  VISIT_UPDATE = 'VISIT_UPDATE',

  VISIT_UPDATE_VISIT_DIAGNOSIS = 'VISIT_UPDATE_VISIT_DIAGNOSIS',
  VISIT_REPLACE_VISIT_PRODUCT_LIST = 'VISIT_REPLACE_VISIT_PRODUCT_LIST',
  VISIT_REPLACE_VISIT_BATCH_LIST = 'VISIT_REPLACE_VISIT_BATCH_LIST',
  VISIT_REPLACE_VISIT_PROCEDURE_LIST = 'VISIT_REPLACE_VISIT_PROCEDURE_LIST',
}
