export enum SOCKET_EVENT {
  SERVER_EMIT_DEMO = 'SERVER_EMIT_DEMO',
  SERVER_EMIT_TICKET_CREATE = 'SERVER_EMIT_TICKET_CREATE',
  CLIENT_EMIT_TICKET_CREATE = 'CLIENT_EMIT_TICKET_CREATE',

  ORGANIZATION_UPDATE = 'ORGANIZATION_UPDATE',
  SETTING_RELOAD = 'SETTING_RELOAD',

  CUSTOMER_UPSERT = 'CUSTOMER_UPSERT',
  DISTRIBUTOR_UPSERT = 'DISTRIBUTOR_UPSERT',
  PRODUCT_UPSERT = 'PRODUCT_UPSERT',
  PRODUCT_LIST_UPDATE = 'PRODUCT_LIST_UPDATE',
  BATCH_UPSERT = 'BATCH_UPSERT',
  BATCH_LIST_UPDATE = 'BATCH_LIST_UPDATE',

  TICKET_CLINIC_CHANGE = 'TICKET_CLINIC_CHANGE',

  TICKET_CLINIC_UPDATE_TICKET_ATTRIBUTE_LIST = 'TICKET_CLINIC_UPDATE_TICKET_ATTRIBUTE_LIST',
  TICKET_CLINIC_CHANGE_TICKET_USER_LIST = 'TICKET_CLINIC_CHANGE_TICKET_USER_LIST',

  TICKET_CLINIC_CHANGE_TICKET_PROCEDURE_LIST = 'TICKET_CLINIC_CHANGE_TICKET_PROCEDURE_LIST',
  TICKET_CLINIC_CHANGE_TICKET_RADIOLOGY_LIST = 'TICKET_CLINIC_CHANGE_TICKET_RADIOLOGY_LIST',
  TICKET_CLINIC_CHANGE_LABORATORY = 'TICKET_CLINIC_CHANGE_LABORATORY',

  TICKET_CLINIC_CHANGE_TICKET_PRODUCT_CONSUMABLE_LIST = 'TICKET_CLINIC_CHANGE_TICKET_PRODUCT_CONSUMABLE_LIST',
  TICKET_CLINIC_CHANGE_TICKET_PRODUCT_PRESCRIPTION_LIST = 'TICKET_CLINIC_CHANGE_TICKET_PRODUCT_PRESCRIPTION_LIST',
}
