export enum SOCKET_EVENT {
  SERVER_EMIT_DEMO = 'SERVER_EMIT_DEMO',
  SERVER_EMIT_TICKET_CREATE = 'SERVER_EMIT_TICKET_CREATE',
  CLIENT_EMIT_TICKET_CREATE = 'CLIENT_EMIT_TICKET_CREATE',

  SOCKET_ORGANIZATION_UPDATE = 'SOCKET_ORGANIZATION_UPDATE',
  SOCKET_SETTING_RELOAD = 'SOCKET_SETTING_RELOAD',

  SOCKET_DISTRIBUTOR_UPSERT = 'SOCKET_DISTRIBUTOR_UPSERT',
  SOCKET_CUSTOMER_UPSERT = 'SOCKET_CUSTOMER_UPSERT',
  SOCKET_PRODUCT_LIST_CHANGE = 'SOCKET_PRODUCT_LIST_CHANGE',
  SOCKET_BATCH_LIST_CHANGE = 'SOCKET_BATCH_LIST_CHANGE',

  SOCKET_PROCEDURE_LIST_CHANGE = 'SOCKET_PROCEDURE_LIST_CHANGE',
  SOCKET_LABORATORY_LIST_CHANGE = 'SOCKET_LABORATORY_LIST_CHANGE',
  SOCKET_RADIOLOGY_LIST_CHANGE = 'SOCKET_RADIOLOGY_LIST_CHANGE',
  SOCKET_POSITION_LIST_CHANGE = 'SOCKET_POSITION_LIST_CHANGE',
  SOCKET_DISCOUNT_LIST_CHANGE = 'SOCKET_DISCOUNT_LIST_CHANGE',

  SOCKET_TICKET_CHANGE = 'SOCKET_TICKET_CHANGE',
  SOCKET_TICKET_LIST_CHANGE = 'SOCKET_TICKET_LIST_CHANGE',

  SOCKET_TICKET_ATTRIBUTE_LIST_CHANGE = 'SOCKET_TICKET_ATTRIBUTE_LIST_CHANGE',
  SOCKET_TICKET_USER_LIST_CHANGE = 'SOCKET_TICKET_USER_LIST_CHANGE',
  SOCKET_TICKET_PROCEDURE_LIST_CHANGE = 'SOCKET_TICKET_PROCEDURE_LIST_CHANGE',
  SOCKET_TICKET_CONSUMABLE_CHANGE = 'SOCKET_TICKET_CONSUMABLE_CHANGE',
  SOCKET_TICKET_PRESCRIPTION_CHANGE = 'SOCKET_TICKET_PRESCRIPTION_CHANGE',
  SOCKET_TICKET_BATCH_LIST_CHANGE = 'SOCKET_TICKET_BATCH_LIST_CHANGE',

  SOCKET_TICKET_LABORATORY_LIST_CHANGE = 'SOCKET_TICKET_LABORATORY_LIST_CHANGE',
  SOCKET_TICKET_RADIOLOGY_LIST_CHANGE = 'SOCKET_TICKET_RADIOLOGY_LIST_CHANGE',
}
