export enum SettingKey {
  GOOGLE_DRIVER = 'GOOGLE_DRIVER',
  SYSTEM_SETTING = 'SYSTEM_SETTING',
  PRODUCT_SETTING = 'PRODUCT_SETTING',
  PRINT_SETTING = 'PRINT_SETTING',

  PRODUCT_UNIT = 'PRODUCT_UNIT',
  PRODUCT_ROUTE = 'PRODUCT_ROUTE',
  PRODUCT_HINT_USAGE = 'PRODUCT_HINT_USAGE',

  INVOICE_SURCHARGE_DETAIL = 'INVOICE_SURCHARGE_DETAIL',
  INVOICE_EXPENSE_DETAIL = 'INVOICE_EXPENSE_DETAIL',

  SCREEN_PRODUCT_LIST = 'SCREEN_PRODUCT_LIST',
  SCREEN_PRODUCT_DETAIL = 'SCREEN_PRODUCT_DETAIL',
  SCREEN_PRODUCT_UPSERT = 'SCREEN_PRODUCT_UPSERT',

  SCREEN_PROCEDURE_LIST = 'SCREEN_PROCEDURE_LIST',
  SCREEN_PROCEDURE_DETAIL = 'SCREEN_PROCEDURE_DETAIL',
  SCREEN_PROCEDURE_UPSERT = 'SCREEN_PROCEDURE_UPSERT',

  SCREEN_LABORATORY_LIST = 'SCREEN_LABORATORY_LIST',
  SCREEN_RADIOLOGY_LIST = 'SCREEN_RADIOLOGY_LIST',

  SCREEN_DISTRIBUTOR_LIST = 'SCREEN_DISTRIBUTOR_LIST',
  SCREEN_DISTRIBUTOR_DETAIL = 'SCREEN_DISTRIBUTOR_DETAIL',
  SCREEN_DISTRIBUTOR_UPSERT = 'SCREEN_DISTRIBUTOR_UPSERT',

  SCREEN_CUSTOMER_LIST = 'SCREEN_CUSTOMER_LIST',
  SCREEN_CUSTOMER_DETAIL = 'SCREEN_CUSTOMER_DETAIL',
  SCREEN_CUSTOMER_UPSERT = 'SCREEN_CUSTOMER_UPSERT',

  SCREEN_RECEIPT_LIST = 'SCREEN_RECEIPT_LIST',
  SCREEN_RECEIPT_DETAIL = 'SCREEN_RECEIPT_DETAIL',
  SCREEN_RECEIPT_UPSERT = 'SCREEN_RECEIPT_UPSERT',

  SCREEN_TICKET_ORDER_LIST = 'SCREEN_TICKET_ORDER_LIST',
  SCREEN_INVOICE_DETAIL = 'SCREEN_INVOICE_DETAIL',
  SCREEN_INVOICE_PREVIEW = 'SCREEN_INVOICE_PREVIEW',
  SCREEN_INVOICE_UPSERT = 'SCREEN_INVOICE_UPSERT',

  APPOINTMENT_LIST = 'APPOINTMENT_LIST',
  APPOINTMENT_UPSERT = 'APPOINTMENT_UPSERT',

  RECEPTION_TICKET_LIST = 'RECEPTION_TICKET_LIST',

  TICKET_CLINIC_LIST = 'TICKET_CLINIC_LIST',
  TICKET_CLINIC_DETAIL = 'TICKET_CLINIC_DETAIL',
  TICKET_CLINIC_CREATE = 'TICKET_CLINIC_CREATE',
  TICKET_STATISTIC = 'TICKET_STATISTIC',
}
