// https://fonts.google.com/icons?icon.size=24&icon.color=%23e8eaed

export { default as IconAddCircle } from './IconAddCircle.vue'
export { default as IconCloudUpload } from './IconCloudUpload.vue'
export { default as IconComputer } from './IconComputer.vue'
export { default as IconDelete } from './IconDelete.vue'
export { default as IconDownload } from './IconDownload.vue'
export { default as IconEditSquare } from './IconEditSquare.vue'
export { default as IconEyeGlasses } from './IconEyeGlasses.vue'
export { default as IconFluid } from './IconFluid.vue'
export { default as IconFluidMed } from './IconFluidMed.vue'
export { default as IconHistory } from './IconHistory.vue'
export { default as IconLabPanel } from './IconLabPanel.vue'
export { default as IconMedicalService } from './IconMedicalService.vue'
export { default as IconPill } from './IconPill.vue'
export { default as IconPulmonology } from './IconPulmonology.vue'
export { default as IconRadiology } from './IconRadiology.vue'
export { default as IconSmartphone } from './IconSmartphone.vue'
export { default as IconStethoscope } from './IconStethoscope.vue'
export { default as IconUndo } from './IconUndo.vue'
export { default as IconUpload } from './IconUpload.vue'
export { default as IconVisibility } from './IconVisibility.vue'
export { default as IconWarehouse } from './IconWarehouse.vue'
