export * from './api/ticket-action.api'
export * from './api/ticket-change-attribute.api'
export * from './api/ticket-change-laboratory.api'
export * from './api/ticket-change-procedure.api'
export * from './api/ticket-change-product.api'
export * from './api/ticket-change-radiology.api'
export * from './api/ticket-change-user.api'
export * from './api/ticket-money.api'
export * from './api/ticket-order.api'
export * from './api/ticket-query.api'
export * from './api/ticket-reception.api'
export * from './ticket.dto'
export * from './ticket.model'
export * from './ticket.service'

